_wandb:
    value:
        cli_version: 0.24.0
        e:
            cricr7wr0dpynhtbgmpcpoxfm6qwkmxx:
                args:
                    - --project_name=Operons for E.coli
                    - --training_parameters_path=training_params.json
                    - --num_epochs=20
                    - --batch_size=64
                    - --init_lr=0.0005
                    - --model_save_name=dna_model_test
                    - --seed=42
                    - --num_workers=4
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 2
                cpu_count_logical: 4
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "103865303040"
                        used: "95927128064"
                email: adrien.le_marchand@etu.minesparis.psl.eu
                executable: /usr/bin/python3
                git:
                    commit: 4b6459eb24c95a6a82c03a978f0d3117fe9ffe49
                    remote: https://github.com/Adri1mines/Operons-for-E.coli.git
                gpu: NVIDIA L4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 7424
                      memoryTotal: "24152899584"
                      name: NVIDIA L4
                      uuid: GPU-6e6df998-d3df-1cee-0d33-d3dc706bc57b
                host: deep-learning3
                memory:
                    total: "16767229952"
                os: Linux-6.8.0-1045-gcp-x86_64-with-glibc2.35
                program: /home/le_marchand_adrien/Operons-for-E.coli/train.py
                python: CPython 3.10.12
                root: /home/le_marchand_adrien/Operons-for-E.coli
                startedAt: "2026-01-25T23:00:45.734482Z"
                writerId: cricr7wr0dpynhtbgmpcpoxfm6qwkmxx
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 106
            "2":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 106
            "4": 3.10.12
            "5": 0.24.0
            "6": 4.57.6
            "12": 0.24.0
            "13": linux-x86_64
training_params:
    value:
        dataset_path: dataset/processed/clean_genome.txt
        val_dataset_size: 0.1
